def test_exceptions():
    assert False